project:
  type: website
  output-dir: docs

# ~ additional metadata excluded for brevity ~

website:
  title: "Mary Holtam"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
  page-navigation: true
  site-url: "https://maryholtam.com"

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual


