---
title: "About Me"
listing:
    type: blog 
    contents: posts
    sort: "date desc"
    type: default 
    categories: true
---

## Education

### Bachelor of Science, Environmental Studies

Concentration in Marine Biology<br> September 2022 - June 2026<br> *University of California, Santa Barbara*

-   Honors college<br>

-   Environmental studies program scholarship recepient

### UC Education Abroad Program, Marine Biology and Terrestrial Ecology

August - November 2024<br> *The University of Queensland, Australia*<br> During this three month program, I gained valuable research and field study experience. I completed two research projects- one focused on fish-feeding patterns and the other on microplastic deposition in sediment. You can find more details about these studies in the projects tab. I also conducted field work in Lamington National Park and Carnarvon Gorge, where I developed practical skills such as species identification, quadrat sampling, and transect surveys.

### Relevant Coursework

Physics, chemistry, biology, oceanography, statistics and data science, calculus, agroecology

## My Work With The Surfrider Foundation

The Surfrider Foundation is a nonprofit organization dedicated to the protection and enjoyment of the world's oceans, waves, and beaches for all people, supported by a powerful activist network. I have been involved with the organization for the past seven years and remain deeply aligned with its goals- from reducing plastic pollution and promoting beach access to protecting clean water. Please continue reading to learn more about my work with the foundation.

### President, Isla Vista Club

2025-present

The Surfrider Foundation Isla Vista club is one of the most active Surfrider student clubs in the world, and among the largest environmental organizations at UCSB. Our club is made up of 125 members and 9 committees. I served as vice president for a year before being elected co-president. My duties and accomplishments in this role include:

-   Increasing club membership by 20% during my vice presidency

-   Collaborating with local brand Island View Outfitters to create a Surfrider-themed collection to raise awareness and funds for our cause

-   Helping to collect over 1,000 dollars worth of prizes for our annual Concert for the Coast fundraiser

-   Planning speaker events with famous world champion surfers, local business owners, and artists

-   Handling club communications, outreach to local businesses and national partners, and recruitment in the fall

### Club Leadership Council Member

2025-present

Selected into a group of 14 Surfrider club leaders from across the country.

-   Monthly meetings and trainings to develop advocacy and leadership skills

-   Presented to legislators at Hill Day in Washington DC and California Oceans Day in Sacramento to advocate for bills that reduce plastic, restrict offshore drilling, and protect clean water.

### Rise Above Plastic Committee Member- Isla Vista Club

2022-2024

Was admitted onto this committee during my freshman year at UCSB and served for a year before being elected vice-president.

-   Canvassed door-to-door to homes in Isla Vista to provide educational materials on recycling

-   Organized petition in support of reduced plastic usage at UCSB dining halls

-   Created weekly "Trash Talk Tuesday" posts to educate Instagram users about plastic and waste reduction

-   Designed sign to post at local beaches that displays the current water quality

### President, La Costa Canyon High School Club

2021-2022

-   Arranged beach cleanups, fundraising campaigns, and biweekly meetings with members

<!-- -->

-   Contacted over fifty San Diego County restaurants to inform them about the Ocean Friendly Restaurants program. Successfully helped to implement this program in multiple restaurants to prioritize plastic reduction, proper recycling, and sustainable food practices.

### Ocean Friendly Restaurants Volunteer, San Diego Chapter

2023 - present

-   Visits and contacts restaurants in San Diego County to inform them about the Ocean Friendly Restaurants program which helps transition eateries to more sustainable practices

-   Tables at events such as beach cleanups to bring awareness to this committee

-   Acted in a training video that is shown to future volunteers

### Plastic Bag Ban Advocate, Surfrider Connecticut

2019

-   Corresponded with Skip the Plastic Norwalk

-   Represented the youth voice by petitioning, presenting, and speaking at city council meetings to successfully campaign for a plastic bag ban in New Canaan and Norwalk, CT

## Professional Experience

## Skills and Certifications

### Relevant Skills

Coding in R, field research, microscope use, working with children, science communication, community outreach, social media management, public speaking, and Spanish

### Certifications

CPR and first aid certified by the American Red Cross<br> California State Seal of Biliteracy in English and Spanish

------------------------------------------------------------------------
