---
title: "Resume"
format: html
---

## Experience

### The Surfrider Foundation

#### President - Isla Vista Club

March 2025- Present<br>

Co-president of one of the largest environmental organizations at UC Santa Barbara containing 9 committees and 120 members. Manages secretarial tasks such as club communications and meeting planning. Plans community events and outreach to local businesses and national partners. Works with the larger Surfrider Foundation to incorporate its goals of protecting the world's oceans, waves, and beaches for all people into the Isla Vista community.

#### Club Leadership Council Member

Jan 2025- Present<br>

Selected into group of 14 Surfrider club leaders from across the country. Monthly meetings and trainings to develop advocacy and leadership skills and share ideas to improve our Surfrider clubs. Presented to legislators at Hill Day in Washington DC and California Oceans Day in Sacramento to advocate for bills that reduce plastic, restrict offshore drilling, and protect clean water.

#### Vice President - Isla Vista Club

Mar 2024- Mar 2025

#### Rise Above Plastics Committee Member

Sep 2022- Mar 2024<br>

Helps to reduce the plastic pollution of the UC Santa Barbara and Isla Vista community through beach cleanups, advocacy, and community events. Organized a petition in support of reduced plastic usage at the UCSB dining halls. Weekly meetings to work to accomplish these goals.

#### Ocean Friendly Restaurants Volunteer

June 2023 - present

Visits and contacts restaurants in San Diego County to inform them about the Ocean Friendly Restaurants program which helps transition eateries to more sustainable practices. Tables at events such as beach cleanups to bring awareness to this committee. Acted in a training video that is shown to future volunteers.

### Rob Machado Foundation

#### Environmental Outreach and Administration Intern

Jun 2024 - Present<br>

Sets up booth and assists volunteers at beach cleanups and community events. Assists with online administrative duties including social media management. Shares information about the foundation's programs and projects to promote environmental stewardship among future generations.

#### Environmental Youth Council Member

Apr 2021 - Jun 2024<br>

One of 8 students admitted. Advocates against the plastic pollution emergency through beach cleanups and recycling campaigns. Operates the foundation’s TikTok account to spread environmental education through video creation. Monthly meetings with foundation board members to evaluate progress & identify goals.

### UC Santa Barbara Surf Team

#### Sustainability Chair

Jun 2024 - Present<br>

Ensures that surf team events are following sustainable practices. Hosts community service events.

### The Sea League

Feb 2024 - Present<br>

Coaches children aged 6-13 in a variety of ocean-related activities including surfing, paddleboarding, tidepooling, and environmental education. Seeks to create an equitable space by removing barriers to ocean accessibility. Inspires young people to care for the ocean.

### UCSB Gauchos Go Green

#### Water Intern

Oct 2023 - Jun 2024<br>

Supports water conservation efforts of the Greek chapters of UC Santa Barbara and the greater Isla Vista community through Meatless Monday campaigns and water-saving challenges.

### Beach Kids Encinitas

#### Beach Camp Instructor

Jun 2022 - Present<br>

Works with 40 six and seven-year-olds each morning in the summer. Teaches ocean safety skills, marine life awareness, and beach games while fostering a love and appreciation for the ocean.

## Education

### UC Santa Barbara

#### Environmental Studies (BS), concentration in marine biology and terrestrial ecology

Expected graduation: June 2026<br>

Activities and societies: Isla Vista Surfrider Foundation, UCSB Surf Team, Kappa Kappa Gamma, College of Letters and Science honors program, Dean's honors list

### The University of Queensland

#### Marine biology and terrestrial ecology

Aug 2024 - Nov 2024<br>

Studied at the UQ campus and research stations across Queensland, Australia through the UC Education Abroad Program. <br>

Conducted research on North Stradbroke Island looking at microplastic distribution among sediment cores and on Heron Island looking at the effects of anthropogenic sea walls on fishing feeding patterns.

### La Costa Canyon High School

Graduated in June 2022<br>

Activities and societies: Surfrider Foundation club president, LCC Surf Team, National Honors Society, LCC Thespian club member

## Languages

### English

Fluent

### Spanish

Professional working capacity<br>

Awarded the Seal of Biliteracy
